#!/bin/bash
set -uo pipefail

echo "--- :snake: Providing conda and job environment"

if [ -z ${CONDA_ROOT+x} ]; then
  echo "Can't find conda root directory. Please set CONDA_ROOT to the local conda root directory."
  exit 1
else
  . ${CONDA_ROOT}/etc/profile.d/conda.sh
  conda activate
fi

if [ -z ${BUILDKITE_PLUGIN_CONDA_ENV+x} ]; then
  if [ -e "environment.yml" ]; then
    CONDA_ENV_FILE="environment.yml"
    CONDA_ENV=$(grep 'name' $CONDA_ENV_FILE | cut -f2 -d ' ')
  fi
  if [ -e ".buildkite/environment.yml" ]; then
    CONDA_ENV_FILE=".buildkite/environment.yml"
    CONDA_ENV=$(grep 'name' $CONDA_ENV_FILE | cut -f2 -d ' ')
  fi
else
  CONDA_ENV=${BUILDKITE_PLUGIN_CONDA_ENV}
fi

if [ -z ${CONDA_ENV+x} ]; then
  echo "No environment specified and no environment.yml file found."
  exit 1
else
  conda activate $CONDA_ENV
  if [ $? -eq 0 ]; then
    :
  else
    if [ -z ${CONDA_ENV_FILE+x} ]; then
      echo "Cannot create environment, missing environment.yml file."
      exit 1
    else
      echo "Creating environment $CONDA_ENV from $CONDA_ENV_FILE."
      conda env create --force -f $CONDA_ENV_FILE || { echo "Failed to create environment."; exit 1; }
      conda activate $CONDA_ENV || { echo "Failed to activate new environment."; exit 1; }
    fi
  fi
fi

echo "--- :terminal: Running commands in the $CONDA_ENV environment"

if type -P ${BUILDKITE_COMMAND%% *} 2>/dev/null 2>&1; then
  eval "${BUILDKITE_COMMAND}"
else
  eval "./${BUILDKITE_COMMAND}"
fi
